#!/bin/bash
#SBATCH -o /projects/bbrz/yirenl2/personalization/logs/multi_vectors_v2_%j.out  # output file (%j expands to jobID)
#SBATCH -e /projects/bbrz/yirenl2/personalization/logs/multi_vectors_v2_%j.err  # error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                      # Request status by email
#SBATCH --mail-user=yirenl2@illinois.edu     # Email address to send results to.
#SBATCH --nodes=1
#SBATCH --mem=32g
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=1
#SBATCH --partition=gpuA100x4
#SBATCH --account=bbrz-delta-gpu
#SBATCH --time=08:00:00
#SBATCH --job-name=multi_vectors_v2
#SBATCH --gpus-per-node=1


# Set project paths
PROJECT_PATH=/projects/bbrz/yirenl2/personalization

# Activate venv
source .venv/bin/activate


# load envs from .env file (need to export the envs to the shell)
export $(cat .env | xargs)

# Add project path to PYTHONPATH so multi_vectors module can be found
export PYTHONPATH=$PROJECT_PATH:$PYTHONPATH

# Run the multi_vectors pipeline
python -m multi_vectors.run_v2 --dataset creative_writing --k 1 --output multi_vectors/outputs_cluster_by_gt --multiplier 0.15 --batch-size 8 --skip-infer-test

# Merge results for validation set
python -m merge multi_vectors/outputs_cluster_by_gt/results/val/creative_writing -o evaluation/dataset/val/creative_writing/multi_vectors_cluster_by_gt_k1_m015_creative_writing_val.csv

# # Merge results for test set
# python -m merge multi_vectors/outputs_cluster_by_gt/results/test/creative_writing -o evaluation/dataset/test/creative_writing/multi_vectors_cluster_by_gt_k3_m015_creative_writing_test.csv

# Run evaluation on validation set
python -m evaluation.run --csv_path evaluation/dataset/val/creative_writing/multi_vectors_cluster_by_gt_k3_m015_creative_writing_val.csv

# # Run evaluation on test set
# python -m evaluation.run --csv_path evaluation/dataset/test/creative_writing/multi_vectors_cluster_by_gt_k3_m015_creative_writing_test.csv

# Deactivate conda environment
conda deactivate

# Unset variables
unset PROJECT_PATH
unset OUTPUT_DIR
