#!/bin/bash
#SBATCH -o /projects/bbrz/yirenl2/personalization/logs/synthesize_writing_samples_%j.out  # output file (%j expands to jobID)
#SBATCH -e /projects/bbrz/yirenl2/personalization/logs/synthesize_writing_samples_%j.err  # error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                      # Request status by email
#SBATCH --mail-user=yirenl2@illinois.edu     # Email address to send results to.
#SBATCH --nodes=1
#SBATCH --mem=32g
#SBATCH --ntasks-per-node=32
#SBATCH --cpus-per-task=1
#SBATCH --partition=gpuA100x4
#SBATCH --account=bbrz-delta-gpu
#SBATCH --time=08:00:00
#SBATCH --job-name=synthesize_writing_samples
#SBATCH --gpus-per-node=1

# Set project paths
PROJECT_PATH=/projects/bbrz/yirenl2/personalization

# Activate venv
source .venv/bin/activate


# load envs from .env file (need to export the envs to the shell)
export $(cat .env | xargs)

# Add project path to PYTHONPATH so synthesis module can be found
export PYTHONPATH=$PROJECT_PATH:$PYTHONPATH

Run the synthesis pipeline
python -m synthesis.run \
    --output_dir ./synthesis/output/creative_writing_more_tasks_less_personas \
    --n_personas 3 \
    --n_scenarios 20 \
    --n_tasks 25 \
    --writing-type "creative story writing"
# python -m synthesis.run \
#     --output_dir ./synthesis/output/social_media_post \
#     --n_personas 10 \
#     --n_scenarios 10 \
#     --n_tasks 10 \
#     --writing-type "social media post"

# Deactivate conda environment
conda deactivate

# Unset variables
unset PROJECT_PATH
unset OUTPUT_DIR
